language: node_js
node_js:
- node
notifications:
  email: false
deploy:
  api_key:
    secure: hPwAWJwJLsPQkb5oxR1ltv8+NPPqi+TUkYJUiLfp2hviswmKjJtMUJr8baYHJtenpK2reUMT28t+UME1eQUl8DsMLQWKT5E/wJLTPpKUIDXZnMtllBUPbqrf9T8F+FUiWux3YQYRWGWPXYpmTWKp+x9eNRcNNSjd4J6jqIZd65LitWK9Wq08bLt4zy3gMEmW4jKIWoe7SXxN6Tz+rRuloeS9MxKTgKSPU0gfrmRcWHjCPzMde8H80Sidv1z/69AHTneH6mk1FnsjLdD44Qgyeg2aDDSOji5S6Ck9t7HzqMtr2p4PNl+6pYZhXgdE6klnzRHs6K8gCMC826X4w9GkKJi/zs31ypwQUK36AelVRxCimCnnxqNQMuhff4x+PHZrJrn5ILFMewbdNVrfphmYajHchUWs7khA0jCrwKdNEwPR3zXuXh+oTLlQKJoihLQKDZl5Wm7L7VogCoI8jC4C7VLlb1iw5TZeNs546EtCO7s5oTbwt/NDFLeZgC8zSh/m8lSTRZvJkVC5ZuAAvsOHE6XTICuLB9GwTE29FHmzqtq29FzYbhNE8tuE6nuinJ+/CE69d75E9ZQzaDlnzVIeIvshziDBSA9Po+ihZ3Eb+ecCMAYZUJLLRyX2ouIbug8hDDpWaNSl0y+e8GeH/Lzi9SrjKxhIGWGf1WxyhKG9QEc=
  app: https://demaceo.githib.io/
  skip_cleanup: true